import Foundation

struct LocationData {
    // List of countries
    static let countries = [
        "Afghanistan",
        "Albania",
        "Algeria",
        "Angola",
        "Anguilla",
        "Antigua and Barbuda",
        "Argentina",
        "Armenia",
        "Australia",
        "Austria",
        "Azerbaijan",
        "Bahamas",
        "Bahrain",
        "Barbados",
        "Belarus",
        "Belgium",
        "Belize",
        "Benin",
        "Bermuda",
        "Bhutan",
        "Bolivia",
        "Bosnia and Herzegovina",
        "Botswana",
        "Brazil",
        "British Virgin Islands",
        "Brunei",
        "Bulgaria",
        "Burkina Faso",
        "Cambodia",
        "Cameroon",
        "Canada",
        "Cape Verde",
        "Cayman Islands",
        "Chad",
        "Chile",
        "China",
        "Colombia",
        "Congo, Democratic Republic of the",
        "Congo, Republic of the",
        "Costa Rica",
        "Côte d'Ivoire",
        "Croatia",
        "Cyprus",
        "Czech Republic",
        "Denmark",
        "Dominica",
        "Dominican Republic",
        "Ecuador",
        "Egypt",
        "El Salvador",
        "Estonia",
        "Eswatini",
        "Fiji",
        "Finland",
        "France",
        "Gabon",
        "Gambia",
        "Georgia",
        "Germany",
        "Ghana",
        "Greece",
        "Grenada",
        "Guatemala",
        "Guinea-Bissau",
        "Guyana",
        "Honduras",
        "Hungary",
        "Iceland",
        "India",
        "Indonesia",
        "Iraq",
        "Ireland",
        "Israel",
        "Italy",
        "Jamaica",
        "Japan",
        "Jordan",
        "Kazakhstan",
        "Kenya",
        "Kosovo",
        "Kuwait",
        "Kyrgyzstan",
        "Laos",
        "Latvia",
        "Lebanon",
        "Liberia",
        "Libya",
        "Lithuania",
        "Luxembourg",
        "Madagascar",
        "Malawi",
        "Malaysia",
        "Maldives",
        "Mali",
        "Malta",
        "Mauritania",
        "Mauritius",
        "Mexico",
        "Micronesia",
        "Moldova",
        "Mongolia",
        "Montenegro",
        "Montserrat",
        "Morocco",
        "Mozambique",
        "Myanmar",
        "Namibia",
        "Nauru",
        "Nepal",
        "Netherlands",
        "New Zealand",
        "Nicaragua",
        "Niger",
        "Nigeria",
        "North Macedonia",
        "Norway",
        "Oman",
        "Pakistan",
        "Palau",
        "Panama",
        "Papua New Guinea",
        "Paraguay",
        "Peru",
        "Philippines",
        "Poland",
        "Portugal",
        "Qatar",
        "Romania",
        "Russia",
        "Rwanda",
        "São Tomé and Príncipe",
        "Saudi Arabia",
        "Senegal",
        "Serbia",
        "Seychelles",
        "Sierra Leone",
        "Singapore",
        "Slovakia",
        "Slovenia",
        "Solomon Islands",
        "South Africa",
        "South Korea",
        "Spain",
        "Sri Lanka",
        "St. Kitts and Nevis",
        "St. Lucia",
        "St. Vincent and the Grenadines",
        "Suriname",
        "Sweden",
        "Switzerland",
        "Taiwan",
        "Tajikistan",
        "Tanzania",
        "Thailand",
        "Tonga",
        "Trinidad and Tobago",
        "Tunisia",
        "Türkiye",
        "Turkmenistan",
        "Turks and Caicos Islands",
        "Uganda",
        "Ukraine",
        "United Arab Emirates",
        "United Kingdom",
        "United States",
        "Uruguay",
        "Uzbekistan",
        "Vanuatu",
        "Venezuela",
        "Vietnam",
        "Yemen",
        "Zambia",
        "Zimbabwe"
    ].sorted()
    
    static let statesAndCities: [String: [String]] = [
        "Alabama": ["Birmingham", "Montgomery", "Mobile", "Huntsville", "Tuscaloosa"],
        "Alaska": ["Anchorage", "Fairbanks", "Juneau", "Sitka", "Ketchikan"],
        "Arizona": ["Phoenix", "Tucson", "Mesa", "Chandler", "Scottsdale", "Glendale", "Tempe"],
        "Arkansas": ["Little Rock", "Fort Smith", "Fayetteville", "Springdale", "Jonesboro"],
        "California": ["Los Angeles", "San Diego", "San Jose", "San Francisco", "Fresno", "Sacramento", "Long Beach", "Oakland", "Bakersfield", "Anaheim", "Santa Ana", "Riverside", "Stockton", "Irvine"],
        "Colorado": ["Denver", "Colorado Springs", "Aurora", "Fort Collins", "Lakewood", "Thornton", "Arvada", "Boulder"],
        "Connecticut": ["Bridgeport", "New Haven", "Stamford", "Hartford", "Waterbury"],
        "Delaware": ["Wilmington", "Dover", "Newark", "Middletown", "Smyrna"],
        "Florida": ["Jacksonville", "Miami", "Tampa", "Orlando", "St. Petersburg", "Hialeah", "Tallahassee", "Fort Lauderdale", "Port St. Lucie", "Cape Coral", "Pembroke Pines", "Hollywood"],
        "Georgia": ["Atlanta", "Augusta", "Columbus", "Macon", "Savannah", "Athens", "Sandy Springs"],
        "Hawaii": ["Honolulu", "Pearl City", "Hilo", "Kailua", "Waipahu"],
        "Idaho": ["Boise", "Meridian", "Nampa", "Idaho Falls", "Pocatello", "Caldwell", "Coeur d'Alene", "Twin Falls"],
        "Illinois": ["Chicago", "Aurora", "Rockford", "Joliet", "Naperville", "Springfield", "Peoria", "Elgin"],
        "Indiana": ["Indianapolis", "Fort Wayne", "Evansville", "South Bend", "Carmel", "Bloomington"],
        "Iowa": ["Des Moines", "Cedar Rapids", "Davenport", "Sioux City", "Iowa City"],
        "Kansas": ["Wichita", "Overland Park", "Kansas City", "Olathe", "Topeka", "Lawrence"],
        "Kentucky": ["Louisville", "Lexington", "Bowling Green", "Owensboro", "Covington"],
        "Louisiana": ["New Orleans", "Baton Rouge", "Shreveport", "Lafayette", "Lake Charles"],
        "Maine": ["Portland", "Lewiston", "Bangor", "South Portland", "Auburn"],
        "Maryland": ["Baltimore", "Frederick", "Rockville", "Gaithersburg", "Bowie", "Annapolis"],
        "Massachusetts": ["Boston", "Worcester", "Springfield", "Cambridge", "Lowell", "Brockton", "Quincy"],
        "Michigan": ["Detroit", "Grand Rapids", "Warren", "Sterling Heights", "Ann Arbor", "Lansing"],
        "Minnesota": ["Minneapolis", "St. Paul", "Rochester", "Duluth", "Bloomington"],
        "Mississippi": ["Jackson", "Gulfport", "Southaven", "Hattiesburg", "Biloxi"],
        "Missouri": ["Kansas City", "St. Louis", "Springfield", "Columbia", "Independence"],
        "Montana": ["Billings", "Missoula", "Great Falls", "Bozeman", "Helena"],
        "Nebraska": ["Omaha", "Lincoln", "Bellevue", "Grand Island", "Kearney"],
        "Nevada": ["Las Vegas", "Henderson", "Reno", "North Las Vegas", "Sparks"],
        "New Hampshire": ["Manchester", "Nashua", "Concord", "Derry", "Dover"],
        "New Jersey": ["Newark", "Jersey City", "Paterson", "Elizabeth", "Edison", "Woodbridge"],
        "New Mexico": ["Albuquerque", "Las Cruces", "Rio Rancho", "Santa Fe", "Roswell"],
        "New York": ["New York City", "Buffalo", "Rochester", "Yonkers", "Syracuse", "Albany", "New Rochelle"],
        "North Carolina": ["Charlotte", "Raleigh", "Greensboro", "Durham", "Winston-Salem", "Fayetteville", "Cary"],
        "North Dakota": ["Fargo", "Bismarck", "Grand Forks", "Minot", "West Fargo"],
        "Ohio": ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron", "Dayton"],
        "Oklahoma": ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow", "Edmond"],
        "Oregon": ["Portland", "Salem", "Eugene", "Gresham", "Hillsboro", "Beaverton"],
        "Pennsylvania": ["Philadelphia", "Pittsburgh", "Allentown", "Erie", "Reading", "Scranton"],
        "Rhode Island": ["Providence", "Warwick", "Cranston", "Pawtucket", "East Providence"],
        "South Carolina": ["Charleston", "Columbia", "North Charleston", "Mount Pleasant", "Rock Hill"],
        "South Dakota": ["Sioux Falls", "Rapid City", "Aberdeen", "Brookings", "Watertown"],
        "Tennessee": ["Nashville", "Memphis", "Knoxville", "Chattanooga", "Clarksville", "Murfreesboro"],
        "Texas": ["Houston", "San Antonio", "Dallas", "Austin", "Fort Worth", "El Paso", "Arlington", "Corpus Christi", "Plano", "Laredo", "Lubbock", "Irving"],
        "Utah": ["Salt Lake City", "West Valley City", "Provo", "West Jordan", "Orem", "Sandy"],
        "Vermont": ["Burlington", "South Burlington", "Rutland", "Barre", "Montpelier"],
        "Virginia": ["Virginia Beach", "Norfolk", "Chesapeake", "Richmond", "Newport News", "Alexandria", "Hampton"],
        "Washington": ["Seattle", "Spokane", "Tacoma", "Vancouver", "Bellevue", "Kent", "Everett"],
        "West Virginia": ["Charleston", "Huntington", "Morgantown", "Parkersburg", "Wheeling"],
        "Wisconsin": ["Milwaukee", "Madison", "Green Bay", "Kenosha", "Racine"],
        "Wyoming": ["Cheyenne", "Casper", "Laramie", "Gillette", "Rock Springs"]
    ]
    
    // Canada provinces and cities
    static let canadianProvincesAndCities: [String: [String]] = [
        "Alberta": ["Calgary", "Edmonton", "Red Deer", "Lethbridge", "Medicine Hat"],
        "British Columbia": ["Vancouver", "Victoria", "Surrey", "Burnaby", "Richmond", "Kelowna"],
        "Manitoba": ["Winnipeg", "Brandon", "Steinbach", "Thompson", "Portage la Prairie"],
        "New Brunswick": ["Moncton", "Saint John", "Fredericton", "Dieppe", "Miramichi"],
        "Newfoundland and Labrador": ["St. John's", "Mount Pearl", "Corner Brook", "Conception Bay South"],
        "Nova Scotia": ["Halifax", "Sydney", "Dartmouth", "Truro", "New Glasgow"],
        "Ontario": ["Toronto", "Ottawa", "Mississauga", "Brampton", "Hamilton", "London", "Markham", "Vaughan", "Kitchener", "Windsor"],
        "Prince Edward Island": ["Charlottetown", "Summerside", "Stratford", "Cornwall"],
        "Quebec": ["Montreal", "Quebec City", "Laval", "Gatineau", "Longueuil", "Sherbrooke", "Saguenay"],
        "Saskatchewan": ["Saskatoon", "Regina", "Prince Albert", "Moose Jaw", "Swift Current"]
    ]
    
    // UK regions and cities
    static let ukRegionsAndCities: [String: [String]] = [
        "England": ["London", "Manchester", "Birmingham", "Leeds", "Liverpool", "Newcastle", "Sheffield", "Bristol", "Leicester", "Nottingham", "Southampton", "Brighton"],
        "Scotland": ["Edinburgh", "Glasgow", "Aberdeen", "Dundee", "Inverness", "Stirling"],
        "Wales": ["Cardiff", "Swansea", "Newport", "Wrexham", "Barry"],
        "Northern Ireland": ["Belfast", "Derry", "Lisburn", "Newry", "Armagh"]
    ]
    
    // Australia states and cities
    static let australianStatesAndCities: [String: [String]] = [
        "New South Wales": ["Sydney", "Newcastle", "Wollongong", "Canberra", "Central Coast"],
        "Victoria": ["Melbourne", "Geelong", "Ballarat", "Bendigo", "Shepparton"],
        "Queensland": ["Brisbane", "Gold Coast", "Sunshine Coast", "Townsville", "Cairns", "Toowoomba"],
        "South Australia": ["Adelaide", "Mount Gambier", "Whyalla", "Murray Bridge"],
        "Western Australia": ["Perth", "Bunbury", "Geraldton", "Albany", "Kalgoorlie"],
        "Tasmania": ["Hobart", "Launceston", "Devonport", "Burnie"],
        "Northern Territory": ["Darwin", "Alice Springs", "Palmerston"],
        "Australian Capital Territory": ["Canberra"]
    ]
    
    // Major cities for countries without state/province structure
    static let majorCitiesByCountry: [String: [String]] = [
        "Germany": ["Berlin", "Munich", "Hamburg", "Frankfurt", "Cologne", "Stuttgart", "Düsseldorf", "Dortmund", "Essen", "Leipzig", "Bremen", "Dresden", "Hanover", "Nuremberg", "Duisburg", "Bochum", "Wuppertal", "Bielefeld", "Bonn", "Münster"],
        "France": ["Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Strasbourg", "Montpellier", "Bordeaux", "Lille", "Rennes", "Reims", "Le Havre", "Saint-Étienne", "Toulon", "Grenoble", "Dijon", "Angers", "Nîmes", "Villeurbanne"],
        "Spain": ["Madrid", "Barcelona", "Valencia", "Seville", "Zaragoza", "Málaga", "Murcia", "Palma", "Las Palmas", "Bilbao", "Alicante", "Córdoba", "Valladolid", "Vigo", "Gijón", "L'Hospitalet", "Granada", "Vitoria-Gasteiz", "Elche", "Oviedo"],
        "Italy": ["Rome", "Milan", "Naples", "Turin", "Palermo", "Genoa", "Bologna", "Florence", "Bari", "Venice", "Verona", "Catania", "Padua", "Trieste", "Brescia", "Taranto", "Prato", "Parma", "Modena", "Reggio Calabria"],
        "Netherlands": ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven", "Tilburg", "Groningen", "Almere", "Breda", "Nijmegen", "Enschede", "Haarlem", "Arnhem", "Zaanstad", "Amersfoort", "'s-Hertogenbosch", "Apeldoorn", "Hoofddorp", "Maastricht", "Leiden"],
        "Belgium": ["Brussels – Capital Region", "Antwerp", "Ghent", "Charleroi", "Liège", "Bruges", "Namur", "Leuven", "Mons", "Mechelen", "Aalst", "La Louvière", "Kortrijk", "Hasselt", "Ostend", "Sint-Niklaas", "Tournai", "Genk", "Seraing", "Roeselare"],
        "Switzerland": ["Zurich", "Geneva", "Basel – City-Canton", "Lausanne", "Bern", "Winterthur", "Lucerne", "St. Gallen", "Lugano", "Biel/Bienne", "Thun", "Köniz", "La Chaux-de-Fonds", "Fribourg", "Schaffhausen", "Chur", "Vernier", "Neuchâtel", "Uster", "Sion"],
        "Austria": ["Vienna – Federal State", "Graz", "Linz", "Salzburg", "Innsbruck", "Klagenfurt", "Villach", "Wels", "Sankt Pölten", "Dornbirn", "Wiener Neustadt", "Steyr", "Feldkirch", "Bregenz", "Leonding", "Klosterneuburg", "Baden", "Wolfsberg", "Leoben", "Krems"],
        "Sweden": ["Stockholm", "Gothenburg", "Malmö", "Uppsala", "Västerås", "Örebro", "Linköping", "Helsingborg", "Jönköping", "Norrköping", "Lund", "Umeå", "Gävle", "Borås", "Södertälje", "Eskilstuna", "Karlstad", "Täby", "Växjö", "Halmstad"],
        "Norway": ["Oslo", "Bergen", "Trondheim", "Stavanger", "Drammen", "Fredrikstad", "Kristiansand", "Sandnes", "Tromsø", "Sarpsborg", "Skien", "Ålesund", "Sandefjord", "Haugesund", "Tønsberg", "Moss", "Porsgrunn", "Bodø", "Arendal", "Hamar"],
        "Denmark": ["Copenhagen", "Aarhus", "Odense", "Aalborg", "Esbjerg", "Randers", "Kolding", "Horsens", "Vejle", "Roskilde", "Herning", "Hørsholm", "Helsingør", "Silkeborg", "Næstved", "Fredericia", "Viborg", "Køge", "Holstebro", "Taastrup"],
        "Finland": ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu", "Turku", "Jyväskylä", "Lahti", "Kuopio", "Pori", "Joensuu", "Lappeenranta", "Hämeenlinna", "Vaasa", "Seinäjoki", "Rovaniemi", "Mikkeli", "Kotka", "Salo", "Porvoo"],
        "Ireland": ["Dublin", "Cork", "Limerick", "Galway", "Waterford", "Drogheda", "Dundalk", "Swords", "Bray", "Navan", "Ennis", "Kilkenny", "Carlow", "Tralee", "Newbridge", "Naas", "Athlone", "Portlaoise", "Mullingar", "Wexford"],
        "Portugal": ["Lisbon", "Porto", "Vila Nova de Gaia", "Amadora", "Braga", "Coimbra", "Funchal", "Setúbal", "Almada", "Agualva-Cacém", "Queluz", "Rio Tinto", "Corroios", "Barreiro", "Évora", "Matosinhos", "Gondomar", "Guimarães", "Odivelas", "Faro"],
        "Greece": ["Athens", "Thessaloniki", "Patras", "Heraklion", "Larissa", "Volos", "Rhodes", "Ioannina", "Chania", "Chalcis", "Agrinio", "Katerini", "Kalamata", "Kavala", "Lamia", "Serres", "Trikala", "Alexandroupoli", "Xanthi", "Kozani"],
        "Poland": ["Warsaw", "Kraków", "Łódź", "Wrocław", "Poznań", "Gdańsk", "Szczecin", "Bydgoszcz", "Lublin", "Białystok", "Katowice", "Gdynia", "Częstochowa", "Radom", "Sosnowiec", "Toruń", "Kielce", "Gliwice", "Zabrze", "Bytom"],
        "Czech Republic": ["Prague", "Brno", "Ostrava", "Plzeň", "Liberec", "Olomouc", "České Budějovice", "Hradec Králové", "Ústí nad Labem", "Pardubice", "Zlín", "Havířov", "Kladno", "Most", "Opava", "Frýdek-Místek", "Jihlava", "Teplice", "Karviná", "Děčín"],
        "Japan": ["Tokyo", "Osaka", "Yokohama", "Nagoya", "Sapporo", "Fukuoka", "Kobe", "Kyoto", "Kawasaki", "Hiroshima", "Sendai", "Chiba", "Kitakyushu", "Sakai", "Niigata", "Hamamatsu", "Kumamoto", "Sagamihara", "Shizuoka", "Okayama", "Okinawa", "Naha"],
        "South Korea": ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Suwon", "Ulsan", "Changwon", "Goyang", "Yongin", "Seongnam", "Cheongju", "Bucheon", "Ansan", "Jeonju", "Cheonan", "Pohang", "Gimhae", "Uijeongbu"],
        "Singapore": ["Singapore"],
        "New Zealand": ["Auckland", "Wellington", "Christchurch", "Hamilton", "Tauranga", "Dunedin", "Palmerston North", "Napier", "Porirua", "Hibiscus Coast", "New Plymouth", "Rotorua", "Whangarei", "Nelson", "Hastings", "Invercargill", "Upper Hutt", "Gisborne", "Blenheim", "Pukekohe"],
        "Mexico": ["Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana", "León", "Juárez", "Cancún", "Zapopan", "Mérida", "San Luis Potosí", "Aguascalientes", "Hermosillo", "Saltillo", "Mexicali", "Culiacán", "Querétaro", "Chihuahua", "Morelia", "Reynosa"],
        "Brazil": ["São Paulo", "Rio de Janeiro", "Brasília – Federal District", "Salvador", "Fortaleza", "Belo Horizonte", "Manaus", "Curitiba", "Recife", "Porto Alegre", "Belém", "Goiânia", "Guarulhos", "Campinas", "São Luís", "São Gonçalo", "Maceió", "Duque de Caxias", "Natal", "Teresina"],
        "Argentina": ["Buenos Aires – Federal District", "Córdoba", "Rosario", "Mendoza", "La Plata", "San Miguel de Tucumán", "Mar del Plata", "Salta", "Santa Fe", "San Juan", "Resistencia", "Santiago del Estero", "Corrientes", "Bahía Blanca", "Posadas", "Paraná", "Neuquén", "Formosa", "San Salvador de Jujuy", "La Rioja"],
        "Chile": ["Santiago", "Valparaíso", "Concepción", "La Serena", "Antofagasta", "Temuco", "Rancagua", "Talca", "Arica", "Chillán", "Iquique", "Puerto Montt", "Los Ángeles", "Coquimbo", "Osorno", "Valdivia", "Punta Arenas", "Quillota", "Quilpué", "Copiapó"],
        "India": ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai", "Kolkata", "Pune", "Ahmedabad", "Jaipur", "Surat", "Lucknow", "Kanpur", "Nagpur", "Indore", "Thane", "Bhopal", "Visakhapatnam", "Patna", "Vadodara", "Ghaziabad"],
        "China": ["Hong Kong – Special Administrative Region", "Macau – Special Administrative Region", "Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Chengdu", "Chongqing", "Tianjin", "Wuhan", "Hangzhou", "Xi'an", "Suzhou", "Zhengzhou", "Nanjing", "Shenyang", "Dongguan", "Changsha", "Harbin", "Qingdao"],
        "Philippines": ["Manila", "Quezon City", "Davao City", "Cebu City", "Caloocan", "Zamboanga City", "Taguig", "Antipolo", "Pasig", "Cagayan de Oro", "Parañaque", "Valenzuela", "Dasmariñas", "Las Piñas", "Makati", "Bacolod", "General Santos", "Muntinlupa", "Bacoor", "Iloilo City"],
        "Thailand": ["Bangkok", "Nonthaburi", "Pak Kret", "Hat Yai", "Chiang Mai", "Udon Thani", "Nakhon Ratchasima", "Surat Thani", "Khon Kaen", "Nakhon Si Thammarat", "Chon Buri", "Rayong", "Lampang", "Phuket", "Songkhla", "Chiang Rai", "Ubon Ratchathani", "Sakon Nakhon", "Samut Prakan", "Nakhon Pathom"],
        "Vietnam": ["Ho Chi Minh City", "Hanoi", "Da Nang", "Hai Phong", "Can Tho", "Bien Hoa", "Hue", "Nha Trang", "Buon Ma Thuot", "Vung Tau", "Nam Dinh", "Phan Thiet", "Long Xuyen", "Ha Long", "Thai Nguyen", "Thanh Hoa", "Rach Gia", "Quy Nhon", "Vinh", "My Tho"],
        "Indonesia": ["Jakarta", "Surabaya", "Bandung", "Bekasi", "Medan", "Tangerang", "Depok", "Semarang", "Palembang", "South Tangerang", "Makassar", "Batam", "Bogor", "Pekanbaru", "Bandar Lampung", "Padang", "Malang", "Denpasar", "Samarinda", "Banjarmasin"],
        "Malaysia": ["Kuala Lumpur", "George Town", "Ipoh", "Shah Alam", "Petaling Jaya", "Johor Bahru", "Malacca City", "Kuching", "Kota Kinabalu", "Seremban", "Kuantan", "Klang", "Alor Setar", "Subang Jaya", "Kota Bharu", "Sandakan", "Miri", "Butterworth", "Kulim", "Taiping"],
        "Taiwan": ["Taipei", "Kaohsiung", "Taichung", "Tainan", "Hsinchu", "Chiayi", "Changhua", "Taoyuan", "Pingtung", "Zhongshan", "Zhongli", "Keelung", "Hualien", "Yilan", "Taitung", "Miaoli", "Nantou", "Yunlin", "Douliu", "Puzi"],
        "South Africa": ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth", "Bloemfontein", "East London", "Pietermaritzburg", "Benoni", "Tembisa", "Vereeniging", "Soweto", "Welkom", "Newcastle", "Krugersdorp", "Boksburg", "Uitenhage", "Roodepoort", "Rustenburg", "Polokwane"],
        "Egypt": ["Cairo", "Alexandria", "Giza", "Shubra El Kheima", "Port Said", "Suez", "Luxor", "Mansoura", "Tanta", "Asyut", "Ismailia", "Faiyum", "Zagazig", "Aswan", "Damietta", "Damanhur", "Minya", "Beni Suef", "Qena", "Sohag"],
        "Kenya": ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret", "Ruiru", "Kikuyu", "Kangundo-Tala", "Malindi", "Naivasha", "Kitui", "Machakos", "Thika", "Garissa", "Kakamega", "Nyeri", "Meru", "Kericho", "Lamu", "Kisii"],
        "Nigeria": ["Lagos", "Kano", "Ibadan", "Abuja", "Port Harcourt", "Benin City", "Kaduna", "Maiduguri", "Zaria", "Aba", "Jos", "Ilorin", "Oyo", "Enugu", "Abeokuta", "Onitsha", "Warri", "Sokoto", "Calabar", "Akure"],
        "Morocco": ["Casablanca", "Rabat", "Fes", "Marrakech", "Tangier", "Agadir", "Meknes", "Oujda", "Kenitra", "Tetouan", "Safi", "Temara", "Mohammedia", "Khouribga", "El Jadida", "Beni Mellal", "Nador", "Taza", "Settat", "Ksar El Kebir"],
        "Afghanistan": ["Kabul", "Kandahar", "Herat", "Mazar-i-Sharif", "Jalalabad", "Kunduz", "Lashkar Gah", "Taloqan", "Puli Khumri", "Ghazni", "Khost", "Farah", "Zaranj", "Shibirghan", "Gardez", "Bamyan", "Faizabad", "Maimana", "Asadabad", "Charikar"],
        "Algeria": ["Algiers", "Oran", "Constantine", "Annaba", "Blida", "Batna", "Djelfa", "Sétif", "Sidi Bel Abbès", "Biskra", "Tébessa", "El Oued", "Skikda", "Tiaret", "Béjaïa", "Tlemcen", "Béchar", "Mostaganem", "Bordj Bou Arréridj", "Chlef"],
        "Angola": ["Luanda", "Huambo", "Lobito", "Benguela", "Lubango", "Kuito", "Malanje", "Namibe", "Soyo", "Cabinda", "Uíge", "Saurimo", "Sumbe", "Menongue", "Mbanza Congo", "Lucapa", "Caála", "Caxito", "N'dalatando", "Ondjiva"],
        "Armenia": ["Yerevan", "Gyumri", "Vanadzor", "Vagharshapat", "Hrazdan", "Abovyan", "Kapan", "Armavir", "Gavar", "Artashat", "Goris", "Charentsavan", "Masis", "Ashtarak", "Ararat", "Ijevan", "Sevan", "Spitak", "Dilijan", "Alaverdi"],
        "Azerbaijan": ["Baku", "Ganja", "Sumqayit", "Mingachevir", "Quba", "Shirvan", "Lankaran", "Nakhchivan", "Shaki", "Yevlakh", "Khankendi", "Barda", "Shamakhi", "Qazakh", "Tovuz", "Salyan", "Khachmaz", "Goychay", "Agdam", "Fizuli"],
        "Bahrain": ["Manama", "Riffa", "Muharraq", "Hamad Town", "A'ali", "Isa Town", "Sitra", "Budaiya", "Jidhafs", "Al-Malikiyah", "Adliya", "Sanabis", "Tubli", "Juffair", "Galali", "Zinj", "Hidd", "Barbar", "Busaiteen", "Bani Jamra"],
        "Benin": ["Cotonou", "Porto-Novo", "Parakou", "Djougou", "Bohicon", "Kandi", "Lokossa", "Ouidah", "Abomey", "Natitingou", "Save", "Malanville", "Sakete", "Nikki", "Banikoara", "Bembereke", "Dogbo", "Come", "Aplahoue", "Tchaourou"],
        "Botswana": ["Gaborone", "Francistown", "Molepolole", "Serowe", "Selibe Phikwe", "Maun", "Kanye", "Mochudi", "Mogoditshane", "Mahalapye", "Palapye", "Tlokweng", "Ramotswa", "Lobatse", "Letlhakane", "Tonota", "Moshupa", "Thamaga", "Jwaneng", "Orapa"],
        "Burkina Faso": ["Ouagadougou", "Bobo-Dioulasso", "Koudougou", "Ouahigouya", "Banfora", "Dedougou", "Kaya", "Tenkodogo", "Hounde", "Fada N'gourma", "Houndé", "Reo", "Gaoua", "Dori", "Manga", "Kongoussi", "Zorgo", "Nouna", "Po", "Diapaga"],
        "Cameroon": ["Douala", "Yaounde", "Bamenda", "Garoua", "Maroua", "Bafoussam", "Ngaoundéré", "Bertoua", "Loum", "Kumba", "Nkongsamba", "Buea", "Foumban", "Mbouda", "Dschang", "Edéa", "Ebolowa", "Kribi", "Tiko", "Limbe"],
        "Cape Verde": ["Praia", "Mindelo", "Santa Maria", "Assomada", "São Filipe", "Pedra Badejo", "Espargos", "Tarrafal", "Ribeira Grande", "Porto Novo", "Cidade Velha", "São Domingos", "Cova Figueira", "Picos", "Nova Sintra", "Mosteiros", "Sal Rei", "Ponta do Sol", "Tarrafal de São Nicolau", "Vila do Maio"],
        "Chad": ["N'Djamena", "Moundou", "Sarh", "Abéché", "Kelo", "Koumra", "Pala", "Am Timan", "Bongor", "Mongo", "Doba", "Ati", "Faya-Largeau", "Massakory", "Moussoro", "Goz Beida", "Biltine", "Laï", "Massaguet", "Bokoro"],
        "Congo, Democratic Republic of the": ["Kinshasa", "Lubumbashi", "Mbuji-Mayi", "Kananga", "Kisangani", "Bukavu", "Goma", "Matadi", "Kolwezi", "Mbandaka", "Kikwit", "Uvira", "Butembo", "Beni", "Tshikapa", "Kalemie", "Likasi", "Kindu", "Bandundu", "Isiro"],
        "Congo, Republic of the": ["Brazzaville", "Pointe-Noire", "Dolisie", "Nkayi", "Impfondo", "Owando", "Ouésso", "Madingou", "Gamboma", "Djambala", "Ewo", "Sibiti", "Kinkala", "Makoua", "Loutété", "Mossendjo", "Sembé", "Boundji", "Loukolela", "Epena"],
        "Côte d'Ivoire": ["Abidjan", "Bouaké", "Daloa", "San-Pédro", "Yamoussoukro", "Korhogo", "Man", "Divo", "Gagnoa", "Abengourou", "Anyama", "Agboville", "Dabou", "Grand-Bassam", "Issia", "Soubré", "Bingerville", "Odienné", "Bondoukou", "Séguéla"],
        "Eswatini": ["Mbabane", "Manzini", "Big Bend", "Malkerns", "Nhlangano", "Siteki", "Piggs Peak", "Lobamba", "Ezulwini", "Hluti", "Simunye", "Bhunya", "Sidvokodvo", "Mhlume", "Tshaneni", "Lavumisa", "Kwaluseni", "Ngwempisi", "Mahamba", "Siphofaneni"],
        "Gabon": ["Libreville", "Port-Gentil", "Franceville", "Oyem", "Moanda", "Mouila", "Lambaréné", "Tchibanga", "Koulamoutou", "Makokou", "Lastoursville", "Mekambo", "Okondja", "Ndendé", "Bitam", "Fougamou", "Gamba", "Mayumba", "Mitzic", "Booué"],
        "Gambia": ["Banjul", "Serekunda", "Brikama", "Bakau", "Farafenni", "Lamin", "Sukuta", "Basse Santa Su", "Gunjur", "Soma", "Bansang", "Kerewan", "Essau", "Georgetown", "Juffureh", "Sanyang", "Barra", "Brufut", "Kartong", "Abuko"],
        "Georgia": ["Tbilisi", "Batumi", "Kutaisi", "Rustavi", "Gori", "Zugdidi", "Poti", "Khashuri", "Samtredia", "Senaki", "Zestaponi", "Marneuli", "Telavi", "Akhaltsikhe", "Kobuleti", "Ozurgeti", "Kaspi", "Chiatura", "Tskaltubo", "Gardabani"],
        "Ghana": ["Accra", "Kumasi", "Tamale", "Sekondi-Takoradi", "Ashaiman", "Cape Coast", "Obuasi", "Teshie", "Madina", "Koforidua", "Wa", "Techiman", "Ho", "Tema", "Nungua", "Sunyani", "Dome", "Bolgatanga", "Bawku", "Taifa"],
        "Guinea-Bissau": ["Bissau", "Bafatá", "Gabú", "Bissorã", "Bolama", "Cacheu", "Catió", "Bubaque", "Mansôa", "Buba", "Farim", "Quinhámel", "Fulacunda", "Quebo", "Bambadinca", "Canchungo", "São Domingos", "Pitche", "Ingore", "Tite"],
        "Iraq": ["Baghdad", "Basra", "Mosul", "Erbil", "Kirkuk", "Najaf", "Karbala", "Nasiriyah", "Amarah", "Duhok", "Sulaymaniyah", "Ramadi", "Kut", "Hillah", "Diwaniyah", "Samawah", "Baqubah", "Tikrit", "Fallujah", "Zakho"],
        "Israel": ["Jerusalem", "Tel Aviv", "Haifa", "Rishon LeZion", "Petah Tikva", "Ashdod", "Netanya", "Be'er Sheva", "Holon", "Bnei Brak", "Ramat Gan", "Rehovot", "Ashkelon", "Bat Yam", "Beit Shemesh", "Kfar Saba", "Herzliya", "Hadera", "Modi'in-Maccabim-Re'ut", "Nazareth"],
        "Jordan": ["Amman", "Zarqa", "Irbid", "Russeifa", "Aqaba", "Madaba", "Salt", "Mafraq", "Jerash", "Karak", "Tafilah", "Ma'an", "Ajloun", "Ramtha", "Fuheis", "Sahab", "Anjara", "Wadi Musa", "Azraq", "Um Qais"],
        "Kuwait": ["Kuwait City", "Hawalli", "Salmiya", "Sabah Al-Salem", "Al Ahmadi", "Al Farwaniyah", "Al Jahra", "Salwa", "Fahaheel", "Mangaf", "Al Fintas", "Bayan", "Mishref", "Rumaithiya", "Ardiya", "Jleeb Al-Shuyoukh", "Mahboula", "Abu Halifa", "Al Qurain", "Kaifan"],
        "Lebanon": ["Beirut", "Tripoli", "Sidon", "Tyre", "Nabatieh", "Jounieh", "Zahle", "Baalbek", "Byblos", "Aley", "Batroun", "Bint Jbeil", "Jezzine", "Halba", "Marjayoun", "Rashaya", "Zahlé", "Anjar", "Hermel", "Deir el Qamar"],
        "Liberia": ["Monrovia", "Gbarnga", "Kakata", "Bensonville", "Harper", "Voinjama", "Buchanan", "Zwedru", "New Yekepa", "Ganta", "Sanniquellie", "Robertsport", "Barclayville", "Fish Town", "Tubmanburg", "Greenville", "Cestos City", "Pleebo", "River Cess", "Bopolu"],
        "Libya": ["Tripoli", "Benghazi", "Misrata", "Bayda", "Zawiya", "Zliten", "Ajdabiya", "Tobruk", "Sabha", "Derna", "Khoms", "Gharyan", "Marj", "Sabratha", "Sirte", "Brak", "Tarhuna", "Zintan", "Murzuq", "Ghat"],
        "Madagascar": ["Antananarivo", "Toamasina", "Antsirabe", "Fianarantsoa", "Mahajanga", "Toliara", "Antsiranana", "Ambovombe", "Morondava", "Sambava", "Manakara", "Farafangana", "Ambanja", "Antalaha", "Nosy Be", "Mananjary", "Ambalavao", "Ihosy", "Maintirano", "Antsohihy"],
        "Malawi": ["Lilongwe", "Blantyre", "Mzuzu", "Zomba", "Kasungu", "Mangochi", "Karonga", "Salima", "Balaka", "Mulanje", "Dedza", "Nkhotakota", "Liwonde", "Thyolo", "Chiradzulu", "Mchinji", "Rumphi", "Ntcheu", "Mzimba", "Nkhata Bay"],
        "Mali": ["Bamako", "Sikasso", "Mopti", "Koutiala", "Ségou", "Kayes", "Gao", "Kati", "Tombouctou", "Markala", "Kidal", "Niono", "Kolokani", "Djenné", "Bougouni", "San", "Banamba", "Bla", "Nioro du Sahel", "Youwarou"],
        "Mauritania": ["Nouakchott", "Nouadhibou", "Néma", "Kaédi", "Rosso", "Zouérat", "Kiffa", "Atar", "Sélibaby", "Aleg", "Akjoujt", "Boutilimit", "Aioun", "Tidjikja", "Bogué", "Ouadane", "Chinguetti", "Moudjéria", "Kankossa", "M'Bout"],
        "Mauritius": ["Port Louis", "Beau Bassin-Rose Hill", "Vacoas-Phoenix", "Curepipe", "Quatre Bornes", "Triolet", "Goodlands", "Centre de Flacq", "Mahebourg", "Saint Pierre", "Bel Air Rivière Sèche", "Grand Baie", "Bambous", "Pamplemousses", "Le Hochet", "Tamarin", "Rivière du Rempart", "Chemin Grenier", "Grand Bois", "Souillac"],
        "Mozambique": ["Maputo", "Matola", "Nampula", "Beira", "Chimoio", "Nacala", "Quelimane", "Tete", "Lichinga", "Pemba", "Gurué", "Xai-Xai", "Maxixe", "Angoche", "Inhambane", "Cuamba", "Montepuez", "Chókwè", "Dondo", "Mocuba"],
        "Namibia": ["Windhoek", "Rundu", "Walvis Bay", "Swakopmund", "Oshakati", "Rehoboth", "Katima Mulilo", "Otjiwarongo", "Ondangwa", "Okahandja", "Grootfontein", "Tsumeb", "Gobabis", "Keetmanshoop", "Mariental", "Outapi", "Ongwediva", "Omaruru", "Karasburg", "Lüderitz"],
        "Niger": ["Niamey", "Zinder", "Maradi", "Agadez", "Tahoua", "Dosso", "Arlit", "Birni N'Konni", "Tessaoua", "Diffa", "Ayorou", "Dakoro", "Dogondoutchi", "Mayahi", "Magaria", "Madaoua", "Tillabéri", "Matameye", "Mirriah", "Gouré"],
        "Oman": ["Muscat", "Salalah", "Sohar", "Nizwa", "Sur", "Buraimi", "Ibri", "Saham", "Barka", "Rustaq", "Khasab", "Bahla", "Al Buraymi", "Shinas", "Izki", "Badiyah", "Suwaiq", "Adam", "Bidiyah", "Jabrin"],
        "Qatar": ["Doha", "Al Rayyan", "Umm Salal", "Al Wakrah", "Al Khor", "Al Shamal", "Mesaieed", "Dukhan", "Lusail", "Al Wukair", "Al Kharrara", "Al Ghuwariyah", "Simaisma", "Al Jumailiya", "Al Thakira", "Al Jemailiya", "Shahaniya", "Rawdat Rashed", "Umm Bab", "Al Karaana"],
        "Rwanda": ["Kigali", "Butare", "Gitarama", "Ruhengeri", "Gisenyi", "Byumba", "Cyangugu", "Kibungo", "Kibuye", "Rwamagana", "Nyanza", "Muhanga", "Karongi", "Musanze", "Huye", "Rubavu", "Rusizi", "Nyagatare", "Kayonza", "Ngoma"],
        "São Tomé and Príncipe": ["São Tomé", "Trindade", "Neves", "Santo Amaro", "Santana", "Guadalupe", "Santa Cruz", "Santo António", "Porto Alegre", "São João dos Angolares", "Ribeira Afonso", "Pantufo", "Micoló", "Santo António do Príncipe", "Santa Catarina", "Água Grande", "Mé-Zóchi", "Caué", "Cantagalo", "Lembá"],
        "Saudi Arabia": ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam", "Khobar", "Tabuk", "Buraidah", "Khamis Mushait", "Hofuf", "Ta'if", "Najran", "Jubail", "Abha", "Yanbu", "Al Qatif", "Sakaka", "Jizan", "Ha'il", "Al Mubarraz"],
        "Senegal": ["Dakar", "Touba", "Thiès", "Kaolack", "Saint-Louis", "Ziguinchor", "Rufisque", "Mbour", "Diourbel", "Louga", "Kolda", "Tambacounda", "Matam", "Sédhiou", "Richard-Toll", "Kayar", "Podor", "Fatick", "Bignona", "Mbacké"],
        "Seychelles": ["Victoria", "Anse Boileau", "Beau Vallon", "Cascade", "Takamaka", "Anse Royale", "Bel Ombre", "Grand Anse Mahé", "English River", "Port Glaud", "Baie Lazare", "Anse Etoile", "Mont Buxton", "Les Mamelles", "Mont Fleuri", "Glacis", "Au Cap", "Pointe La Rue", "Roche Caiman", "Saint Louis"],
        "Sierra Leone": ["Freetown", "Bo", "Kenema", "Koidu", "Makeni", "Lunsar", "Port Loko", "Waterloo", "Kabala", "Kambia", "Kailahun", "Bonthe", "Moyamba", "Magburaka", "Yengema", "Lungi", "Pujehun", "Segbwema", "Koindu", "Zimmi"],
        "Tanzania": ["Dar es Salaam", "Mwanza", "Arusha", "Dodoma", "Mbeya", "Morogoro", "Tanga", "Zanzibar City", "Kigoma", "Moshi", "Tabora", "Bukoba", "Musoma", "Songea", "Iringa", "Singida", "Shinyanga", "Sumbawanga", "Lindi", "Mpanda"],
        "Tunisia": ["Tunis", "Sfax", "Sousse", "Kairouan", "Bizerte", "Gabès", "Ariana", "La Soukra", "Gafsa", "Monastir", "Ben Arous", "Kasserine", "Médenine", "Mahdia", "La Marsa", "Nabeul", "Tataouine", "Béja", "Jendouba", "Tozeur"],
        "Uganda": ["Kampala", "Gulu", "Lira", "Mbarara", "Jinja", "Bwizibwera", "Mbale", "Mukono", "Kasese", "Masaka", "Entebbe", "Njeru", "Kitgum", "Fort Portal", "Hoima", "Soroti", "Arua", "Kabale", "Tororo", "Masindi"],
        "United Arab Emirates": ["Dubai", "Abu Dhabi", "Sharjah", "Al Ain", "Ajman", "Ras Al Khaimah", "Fujairah", "Umm Al Quwain", "Khor Fakkan", "Dhaid", "Dibba Al-Fujairah", "Dibba Al-Hisn", "Kalba", "Madinat Zayed", "Ar-Rams", "Jebel Ali", "Al Madam", "Hatta", "Liwa Oasis", "Ghayathi"],
        "Yemen": ["Sana'a", "Aden", "Ta'izz", "Hodeidah", "Ibb", "Dhamar", "Al Mukalla", "Zinjibar", "Saada", "Ataq", "Al Bayda", "Al Hazm", "Marib", "Hajjah", "Amran", "Lahij", "Sayyan", "Rada'a", "Al Ghaydah", "Zabid"],
        "Zambia": ["Lusaka", "Kitwe", "Ndola", "Kabwe", "Chingola", "Mufulira", "Livingstone", "Luanshya", "Kasama", "Chipata", "Solwezi", "Mansa", "Mongu", "Choma", "Kapiri Mposhi", "Mazabuka", "Kalulushi", "Chililabombwe", "Nchelenge", "Mpika"],
        "Zimbabwe": ["Harare", "Bulawayo", "Chitungwiza", "Mutare", "Gweru", "Epworth", "Kwekwe", "Kadoma", "Masvingo", "Chinhoyi", "Norton", "Marondera", "Ruwa", "Chegutu", "Zvishavane", "Bindura", "Beitbridge", "Redcliff", "Victoria Falls", "Hwange"],
        "Albania": ["Tirana", "Durrës", "Vlorë", "Elbasan", "Shkodër", "Fier", "Korçë", "Berat", "Lushnjë", "Kavajë", "Pogradec", "Laç", "Kukës", "Krujë", "Lezhë", "Patos", "Gjirokastër", "Sarandë", "Peshkopi", "Burrel"],
        "Belarus": ["Minsk", "Gomel", "Mogilev", "Vitebsk", "Grodno", "Brest", "Bobruisk", "Baranovichi", "Borisov", "Pinsk", "Orsha", "Mozyr", "Soligorsk", "Novopolotsk", "Lida", "Polotsk", "Molodechno", "Slutsk", "Rechytsa", "Svetlogorsk"],
        "Bosnia and Herzegovina": ["Sarajevo", "Banja Luka", "Tuzla", "Zenica", "Mostar", "Bijeljina", "Brčko", "Prijedor", "Trebinje", "Cazin", "Doboj", "Travnik", "Gradiška", "Srebrenica", "Goražde", "Konjic", "Visoko", "Bugojno", "Zavidovići", "Živinice"],
        "Bulgaria": ["Sofia", "Plovdiv", "Varna", "Burgas", "Ruse", "Stara Zagora", "Pleven", "Sliven", "Dobrich", "Shumen", "Pernik", "Haskovo", "Yambol", "Pazardzhik", "Blagoevgrad", "Veliko Tarnovo", "Vratsa", "Gabrovo", "Asenovgrad", "Vidin"],
        "Croatia": ["Zagreb", "Split", "Rijeka", "Osijek", "Zadar", "Slavonski Brod", "Pula", "Sesvete", "Karlovac", "Varaždin", "Šibenik", "Sisak", "Dubrovnik", "Velika Gorica", "Vukovar", "Bjelovar", "Koprivnica", "Samobor", "Čakovec", "Vinkovci"],
        "Cyprus": ["Nicosia", "Limassol", "Larnaca", "Famagusta", "Paphos", "Kyrenia", "Protaras", "Paralimni", "Morphou", "Ayia Napa", "Polis", "Dhekelia", "Peyia", "Geroskipou", "Aradhippou", "Aradippou", "Livadia", "Kiti", "Xylofagou", "Ypsonas"],
        "Estonia": ["Tallinn", "Tartu", "Narva", "Pärnu", "Kohtla-Järve", "Viljandi", "Rakvere", "Maardu", "Sillamäe", "Kuressaare", "Võru", "Valga", "Haapsalu", "Jõhvi", "Paide", "Keila", "Kiviõli", "Tapa", "Põlva", "Türi"],
        "Hungary": ["Budapest", "Debrecen", "Szeged", "Miskolc", "Pécs", "Győr", "Nyíregyháza", "Kecskemét", "Székesfehérvár", "Szombathely", "Szolnok", "Tatabánya", "Kaposvár", "Érd", "Veszprém", "Békéscsaba", "Zalaegerszeg", "Sopron", "Eger", "Nagykanizsa"],
        "Iceland": ["Reykjavík", "Kópavogur", "Hafnarfjörður", "Akureyri", "Reykjanesbær", "Garðabær", "Mosfellsbær", "Árborg", "Akranes", "Fjarðabyggð", "Ísafjörður", "Vestmannaeyjar", "Grindavík", "Hveragerði", "Selfoss", "Borgarnes", "Egilsstaðir", "Húsavík", "Siglufjörður", "Sauðárkrókur"],
        "Kosovo": ["Pristina", "Prizren", "Ferizaj", "Peja", "Gjakova", "Gjilan", "Mitrovica", "Podujevo", "Vushtrri", "Suva Reka", "Lipjan", "Rahovec", "Drenas", "Kaçanik", "Malisheva", "Kamenica", "Istog", "Shtime", "Skenderaj", "Kline"],
        "Latvia": ["Riga", "Daugavpils", "Liepāja", "Jelgava", "Jūrmala", "Ventspils", "Rēzekne", "Valmiera", "Ogre", "Jēkabpils", "Tukums", "Salaspils", "Cēsis", "Kuldīga", "Olaine", "ikste", "Saldus", "Talsi", "Bauska", "Dobele"],
        "Lithuania": ["Vilnius", "Kaunas", "Klaipėda", "Šiauliai", "Panevėžys", "Alytus", "Marijampolė", "Mažeikiai", "Jonava", "Utena", "Kėdainiai", "Telšiai", "Visaginas", "Tauragė", "Ukmergė", "Plungė", "Kretinga", "Šilutė", "Radviliškis", "Palanga"],
        "Luxembourg": ["Luxembourg City", "Esch-sur-Alzette", "Dudelange", "Schifflange", "Bettembourg", "Pétange", "Ettelbruck", "Diekirch", "Strassen", "Bertrange", "Sanem", "Hesperange", "Differdange", "Mamer", "Mersch", "Wiltz", "Echternach", "Grevenmacher", "Remich", "Vianden"],
        "Malta": ["Valletta", "Birkirkara", "Mosta", "Qormi", "Żabbar", "Sliema", "St. Paul's Bay", "Naxxar", "San Ġwann", "Fgura", "Żejtun", "Ħamrun", "Rabat", "Marsaskala", "Attard", "Mellieħa", "Paola", "Swieqi", "Marsa", "Żurrieq"],
        "Moldova": ["Chișinău", "Tiraspol", "Bălți", "Bender", "Rîbnița", "Cahul", "Ungheni", "Soroca", "Orhei", "Comrat", "Ceadîr-Lunga", "Strășeni", "Edineț", "Drochia", "Căușeni", "Hîncești", "Soroca", "Florești", "Cimișlia", "Vulcănești"],
        "Montenegro": ["Podgorica", "Nikšić", "Pljevlja", "Bijelo Polje", "Cetinje", "Bar", "Herceg Novi", "Berane", "Budva", "Ulcinj", "Tivat", "Rožaje", "Kotor", "Danilovgrad", "Mojkovac", "Plav", "Kolašin", "Žabljak", "Petnjica", "Gusinje"],
        "North Macedonia": ["Skopje", "Bitola", "Kumanovo", "Prilep", "Tetovo", "Veles", "Ohrid", "Gostivar", "Štip", "Strumica", "Kavadarci", "Kočani", "Kičevo", "Struga", "Radoviš", "Gevgelija", "Debar", "Negotino", "Sveti Nikole", "Berovo"],
        "Romania": ["Bucharest", "Cluj-Napoca", "Timișoara", "Iași", "Constanța", "Craiova", "Brașov", "Galați", "Ploiești", "Oradea", "Brăila", "Arad", "Pitești", "Sibiu", "Bacău", "Târgu Mureș", "Baia Mare", "Buzău", "Botoșani", "Satu Mare"],
        "Russia": ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan", "Nizhny Novgorod", "Chelyabinsk", "Samara", "Omsk", "Rostov-on-Don", "Ufa", "Krasnoyarsk", "Voronezh", "Perm", "Volgograd", "Krasnodar", "Saratov", "Tyumen", "Tolyatti", "Izhevsk"],
        "Serbia": ["Belgrade", "Novi Sad", "Niš", "Kragujevac", "Subotica", "Zrenjanin", "Pančevo", "Čačak", "Novi Pazar", "Kraljevo", "Smederevo", "Leskovac", "Užice", "Vranje", "Valjevo", "Kruševac", "Šabac", "Sombor", "Požarevac", "Pirot"],
        "Slovakia": ["Bratislava", "Košice", "Prešov", "Žilina", "Banská Bystrica", "Nitra", "Trnava", "Trenčín", "Martin", "Poprad", "Prievidza", "Zvolen", "Považská Bystrica", "Michalovce", "Spišská Nová Ves", "Komárno", "Levice", "Humenné", "Bardejov", "Liptovský Mikuláš"],
        "Slovenia": ["Ljubljana", "Maribor", "Celje", "Kranj", "Velenje", "Koper", "Novo Mesto", "Ptuj", "Trbovlje", "Kamnik", "Jesenice", "Nova Gorica", "Domžale", "Škofja Loka", "Slovenj Gradec", "Izola", "Murska Sobota", "Krško", "Postojna", "Vrhnika"],
        "Türkiye": ["Istanbul", "Ankara", "Izmir", "Bursa", "Antalya", "Adana", "Konya", "Gaziantep", "Şanlıurfa", "Kocaeli", "Mersin", "Diyarbakır", "Kayseri", "Eskişehir", "Samsun", "Denizli", "Adapazarı", "Malatya", "Kahramanmaraş", "Erzurum"],
        "Ukraine": ["Kyiv", "Kharkiv", "Odesa", "Dnipro", "Donetsk", "Zaporizhzhia", "Lviv", "Kryvyi Rih", "Mykolaiv", "Mariupol", "Luhansk", "Vinnytsia", "Simferopol", "Sevastopol", "Kherson", "Poltava", "Chernihiv", "Cherkasy", "Sumy", "Zhytomyr"],
        "Anguilla": ["The Valley", "Blowing Point", "Sandy Ground", "Sandy Hill", "The Quarter", "North Side", "East End", "West End", "South Hill", "Island Harbour", "Stoney Ground", "George Hill", "North Hill", "Farrington", "Rey Hill", "Little Harbour", "Crocus Hill", "Long Bay", "Shoal Bay", "Savannah Bay"],
        "Antigua and Barbuda": ["St. John's", "All Saints", "Liberta", "Potter's Village", "Bolans", "Swetes", "Seaview Farm", "Pigotts", "Parham", "English Harbour", "Falmouth", "Old Road", "Freetown", "Willikies", "Codrington", "Cedar Grove", "Bethesda", "Five Islands", "Jennings", "Urlings"],
        "Bahamas": ["Nassau", "Freeport", "West End", "Coopers Town", "Marsh Harbour", "Dunmore Town", "Rock Sound", "High Rock", "George Town", "Colonel Hill", "Cockburn Town", "San Andros", "Spanish Wells", "Alice Town", "Matthew Town", "Arthurs Town", "Port Nelson", "Abraham's Bay", "Black Point", "Duncan Town"],
        "Barbados": ["Bridgetown", "Speightstown", "Oistins", "Bathsheba", "Holetown", "Six Cross Roads", "The Crane", "Crab Hill", "Greenland", "Worthing", "Hastings", "Rockley", "St. Lawrence", "Dover", "Sunset Crest", "Paynes Bay", "Mullins", "Belleplaine", "Cattlewash", "Martin's Bay"],
        "Belize": ["Belize City", "San Ignacio", "Orange Walk", "Belmopan", "Dangriga", "Corozal", "San Pedro", "Benque Viejo del Carmen", "Punta Gorda", "Caye Caulker", "Hopkins", "Placencia", "Ladyville", "Independence", "Sarteneja", "Shipyard", "Valley of Peace", "Bullet Tree Falls", "Santa Elena", "Maskall"],
        "Bermuda": ["Hamilton", "St. George's", "Somerset", "Flatts Village", "Tucker's Town", "Bailey's Bay", "Warwick", "Devonshire", "Paget", "Pembroke", "Sandys", "Southampton", "Smiths", "Spanish Point", "Harrington Sound", "St. David's", "Dockyard", "Shelly Bay", "Ely's Harbour", "Mangrove Bay"],
        "Bolivia": ["La Paz", "Santa Cruz", "Cochabamba", "Sucre", "Oruro", "Tarija", "Potosí", "Sacaba", "Montero", "Trinidad", "Riberalta", "Warnes", "Yacuiba", "Quillacollo", "Cobija", "Llallagua", "Camiri", "Bermejo", "Villamontes", "Tupiza"],
        "British Virgin Islands": ["Road Town", "Spanish Town", "The Valley", "West End", "East End", "Great Harbour", "Carrot Bay", "Cane Garden Bay", "Long Bay", "Beef Island", "Josiah's Bay", "Fat Hog's Bay", "Little Harbour", "Port Purcell", "Handsome Bay", "Cappoons Bay", "Sea Cows Bay", "Smuggler's Cove", "Brewers Bay", "Nail Bay"],
        "Cayman Islands": ["George Town", "West Bay", "Bodden Town", "North Side", "East End", "Savannah", "Spotts", "Prospect", "South Sound", "Gun Bay", "Breakers", "Colliers", "Cayman Brac", "Little Cayman", "Lower Valley", "Stake Bay", "Spot Bay", "Creek", "Newlands", "Red Bay"],
        "Colombia": ["Bogotá", "Medellín", "Cali", "Barranquilla", "Cartagena", "Cúcuta", "Bucaramanga", "Pereira", "Santa Marta", "Ibagué", "Pasto", "Manizales", "Neiva", "Soledad", "Villavicencio", "Armenia", "Soacha", "Valledupar", "Montería", "Itagüí"],
        "Costa Rica": ["San José", "Limón", "San Francisco", "Alajuela", "Liberia", "Paraíso", "Puntarenas", "San Vicente", "San Isidro", "Heredia", "Curridabat", "San Felipe", "Desamparados", "Cartago", "Aserrí", "San Rafael", "Esparza", "Quesada", "Nicoya", "Grecia"],
        "Dominica": ["Roseau", "Portsmouth", "Marigot", "Berekua", "Mahaut", "Saint Joseph", "Wesley", "Soufrière", "La Plaine", "Grand Bay", "Salisbury", "Canefield", "Pointe Michel", "Calibishie", "Scotts Head", "Castle Bruce", "Colihaut", "Massacre", "Loubiere", "Vieille Case"],
        "Dominican Republic": ["Santo Domingo", "Santiago de los Caballeros", "Santo Domingo Oeste", "Santo Domingo Este", "San Pedro de Macorís", "La Romana", "Bella Vista", "San Cristóbal", "Puerto Plata", "San Francisco de Macorís", "Higüey", "La Vega", "Concepción de La Vega", "Moca", "Bonao", "Baní", "Boca Chica", "San Juan", "Azua", "Mao"],
        "Ecuador": ["Quito", "Guayaquil", "Cuenca", "Santo Domingo", "Machala", "Durán", "Portoviejo", "Manta", "Loja", "Ambato", "Esmeraldas", "Quevedo", "Riobamba", "Milagro", "Ibarra", "La Libertad", "Babahoyo", "Sangolquí", "Latacunga", "Daule"],
        "El Salvador": ["San Salvador", "Soyapango", "Santa Ana", "San Miguel", "Mejicanos", "Apopa", "Delgado", "Sonsonate", "San Marcos", "Ilopango", "Ahuachapán", "Cuscatancingo", "Chalatenango", "Antiguo Cuscatlán", "Ayutuxtepeque", "Zacatecoluca", "Usulután", "La Unión", "San Martín", "Cojutepeque"],
        "Grenada": ["St. George's", "Gouyave", "Grenville", "Victoria", "Sauteurs", "Hillsborough", "St. David's", "Grand Roy", "Woburn", "Constantine", "Telescope", "Perdmontemps", "Munich", "Beaulieu", "Conference", "Marquis", "Bathway", "Birch Grove", "Belmont", "Mt. Moritz"],
        "Guatemala": ["Guatemala City", "Mixco", "Villa Nueva", "Petapa", "San Juan Sacatepéquez", "Quetzaltenango", "Villa Canales", "Escuintla", "Chinautla", "Chimaltenango", "Huehuetenango", "Amatitlán", "Totonicapán", "Santa Lucía Cotzumalguapa", "Puerto Barrios", "San Francisco El Alto", "Cobán", "Chichicastenango", "Antigua Guatemala", "Jalapa"],
        "Guyana": ["Georgetown", "Linden", "New Amsterdam", "Anna Regina", "Bartica", "Skeldon", "Rosignol", "Mahaica Village", "Parika", "Vreed-en-Hoop", "Charity", "Lethem", "Mahaicony", "Fort Wellington", "Mahdia", "Rose Hall", "Albion", "Corriverton", "Springlands", "Ituni"],
        "Honduras": ["Tegucigalpa", "San Pedro Sula", "Choloma", "La Ceiba", "El Progreso", "Choluteca", "Comayagua", "Puerto Cortés", "La Lima", "Danlí", "Siguatepeque", "Juticalpa", "Tocoa", "Villanueva", "Tela", "Olanchito", "Santa Rosa de Copán", "Potrerillos", "Cofradía", "La Paz"],
        "Jamaica": ["Kingston", "Spanish Town", "Portmore", "Montego Bay", "May Pen", "Mandeville", "Old Harbour", "Savanna-la-Mar", "Ocho Rios", "Port Antonio", "Linstead", "Half Way Tree", "Morant Bay", "Santa Cruz", "Black River", "Falmouth", "Lucea", "Port Maria", "Annotto Bay", "Brown's Town"],
        "Montserrat": ["Brades", "Little Bay", "St. Peter's", "St. John's", "Salem", "Woodlands", "Olveston", "Lookout", "Cudjoe Head", "Davy Hill", "Gerald's", "St. Patrick's", "Harris", "Richmond Hill", "Cork Hill", "Friths", "Cavalla Hill", "Judy Piece", "St. Georges Hill", "Old Towne"],
        "Nicaragua": ["Managua", "León", "Masaya", "Matagalpa", "Chinandega", "Estelí", "Tipitapa", "Granada", "Jinotega", "Juigalpa", "Ciudad Sandino", "Bluefields", "Nueva Guinea", "Ocotal", "Rivas", "Somoto", "Boaco", "Diriamba", "Jinotepe", "Puerto Cabezas"],
        "Panama": ["Panama City", "San Miguelito", "Tocumen", "David", "Arraiján", "Colón", "Las Cumbres", "La Chorrera", "Pacora", "Santiago", "Chitré", "Penonomé", "La Concepción", "Aguadulce", "Changuinola", "Vista Alegre", "Balboa", "Puerto Armuelles", "Ancón", "Bugaba"],
        "Paraguay": ["Asunción", "Ciudad del Este", "San Lorenzo", "Luque", "Capiatá", "Lambaré", "Fernando de la Mora", "Limpio", "Ñemby", "Encarnación", "Mariano Roque Alonso", "Pedro Juan Caballero", "Presidente Franco", "Itauguá", "Villa Elisa", "San Antonio", "Caaguazú", "Coronel Oviedo", "Concepción", "Villarrica"],
        "Peru": ["Lima", "Arequipa", "Callao", "Trujillo", "Chiclayo", "Iquitos", "Huancayo", "Piura", "Chimbote", "Cusco", "Pucallpa", "Tacna", "Ica", "Juliaca", "Sullana", "Chincha Alta", "Ayacucho", "Cajamarca", "Puno", "Tarapoto"],
        "St. Kitts and Nevis": ["Basseterre", "Charlestown", "Cayon", "Dieppe Bay Town", "Sandy Point Town", "Old Road Town", "Middle Island", "Monkey Hill", "Newcastle", "Gingerland", "Cotton Ground", "Fig Tree", "Sadlers", "St. Paul's", "Trinity", "Tabernacle", "Lodge", "Fountain", "Boyd's", "Ponds Pasture"],
        "St. Lucia": ["Castries", "Vieux Fort", "Micoud", "Soufrière", "Dennery", "Gros Islet", "Anse la Raye", "Laborie", "Choiseul", "Canaries", "Anse-la-Raye", "Praslin", "Mon Repos", "Babonneau", "Desruisseaux", "Fond", "Ti Rocher", "Beausejour", "Grand Riviere", "Augier"],
        "St. Vincent and the Grenadines": ["Kingstown", "Georgetown", "Barrouallie", "Port Elizabeth", "Chateaubelair", "Byera Village", "Biabou", "Layou", "Calliaqua", "Arnos Vale", "Mesopotamia", "Canouan", "Bequia", "Union Island", "Mayreau", "Mustique", "Colonarie", "Richland Park", "Stubbs", "Vermont"],
        "Suriname": ["Paramaribo", "Lelydorp", "Brokopondo", "Nieuw Nickerie", "Moengo", "Nieuw Amsterdam", "Mariënburg", "Wageningen", "Albina", "Groningen", "Brownsweg", "Onverwacht", "Totness", "Coronie", "Friendship", "Tamanredjo", "Meerzorg", "Commewijne", "Flora", "Jarikaba"],
        "Trinidad and Tobago": ["Port of Spain", "Chaguanas", "San Fernando", "Arima", "Marabella", "Point Fortin", "San Juan", "Tunapuna", "Couva", "Princes Town", "Sangre Grande", "Diego Martin", "Penal", "Scarborough", "Arouca", "Debe", "Rio Claro", "Siparia", "La Brea", "Plymouth"],
        "Turks and Caicos Islands": ["Cockburn Town", "Providenciales", "Five Cays", "Kew", "Blue Hills", "The Bight", "Grace Bay", "Long Bay", "Whitby", "North Caicos", "Middle Caicos", "South Caicos", "Salt Cay", "Grand Turk", "Pine Cay", "Parrot Cay", "Dellis Cay", "Bottle Creek", "Conch Bar", "Lorimers"],
        "Uruguay": ["Montevideo", "Salto", "Paysandú", "Las Piedras", "Rivera", "Maldonado", "Tacuarembó", "Melo", "Mercedes", "Artigas", "Minas", "San José de Mayo", "Durazno", "Florida", "Barros Blancos", "Ciudad de la Costa", "Treinta y Tres", "Rocha", "San Carlos", "Pando"],
        "Venezuela": ["Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Maracay", "Ciudad Guayana", "Barcelona", "Maturín", "Puerto La Cruz", "Petare", "Turmero", "Ciudad Bolívar", "Mérida", "Santa Teresa del Tuy", "Cabimas", "Cumaná", "Los Teques", "Barinas", "Guarenas", "San Cristóbal"],
        "Bhutan": ["Thimphu", "Phuntsholing", "Paro", "Punakha", "Wangdue Phodrang", "Jakar", "Samdrup Jongkhar", "Gelephu", "Trashigang", "Mongar", "Trongsa", "Pemagatshel", "Zhemgang", "Lhuntse", "Samtse", "Dagana", "Haa", "Gasa", "Bumthang", "Trashi Yangtse"],
        "Brunei": ["Bandar Seri Begawan", "Kuala Belait", "Seria", "Tutong", "Bangar", "Jerudong", "Lumapas", "Mentiri", "Serasa", "Kampong Ayer", "Berakas", "Gadong", "Kota Batu", "Sengkurong", "Labi", "Lamunin", "Bukit Sawat", "Temburong", "Muara", "Panaga"],
        "Cambodia": ["Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville", "Kampong Cham", "Prey Veng", "Ta Khmau", "Kampong Speu", "Pursat", "Kampong Thom", "Svay Rieng", "Kratie", "Kampong Chhnang", "Stung Treng", "Kampot", "Kep", "Pailin", "Takeo", "Preah Vihear", "Banlung"],
        "Fiji": ["Suva", "Lautoka", "Nadi", "Labasa", "Ba", "Nasinu", "Nausori", "Sigatoka", "Tavua", "Levuka", "Savusavu", "Lami", "Vatukoula", "Rakiraki", "Korovou", "Navua", "Taveuni", "Seaqaqa", "Vunidawa", "Naceva"],
        "Kazakhstan": ["Almaty", "Nur-Sultan", "Shymkent", "Karaganda", "Aktobe", "Taraz", "Pavlodar", "Ust-Kamenogorsk", "Semey", "Atyrau", "Kostanay", "Kyzylorda", "Uralsk", "Petropavl", "Aktau", "Temirtau", "Turkestan", "Kokshetau", "Taldykorgan", "Ekibastuz"],
        "Kyrgyzstan": ["Bishkek", "Osh", "Jalal-Abad", "Karakol", "Tokmok", "Uzgen", "Naryn", "Talas", "Batken", "Kara-Balta", "Balykchy", "Kant", "Kyzyl-Kiya", "Toktogul", "Kara-Suu", "Cholpon-Ata", "Isfana", "At-Bashi", "Suluktu", "Mailuu-Suu"],
        "Laos": ["Vientiane", "Pakse", "Savannakhet", "Luang Prabang", "Thakhek", "Xam Neua", "Phonsavan", "Muang Xay", "Salavan", "Xaignabouli", "Attapeu", "Houayxay", "Luang Namtha", "Phongsali", "Saravan", "Pakxan", "Sekong", "Vang Vieng", "Tha Khaek", "Ban Houayxay"],
        "Maldives": ["Malé", "Addu City", "Fuvahmulah", "Kulhudhuffushi", "Thinadhoo", "Naifaru", "Dhidhdhoo", "Mahibadhoo", "Veymandoo", "Muli", "Eydhafushi", "Fonadhoo", "Nilandhoo", "Ugoofaaru", "Hulhumalé", "Vilimalé", "Hithadhoo", "Feydhoo", "Maradhoo", "Gan"],
        "Micronesia": ["Palikir", "Weno", "Kolonia", "Tofol", "Colonia", "Moen", "Ulithi", "Nukuoro", "Kapingamarangi", "Pingelap", "Mokil", "Ngatik", "Sapwuahfik", "Nama", "Uman", "Fananu", "Oneop", "Piis-Panewu", "Tomil", "Lelu"],
        "Mongolia": ["Ulaanbaatar", "Erdenet", "Darkhan", "Choibalsan", "Mörön", "Khovd", "Ölgii", "Ulaangom", "Bayankhongor", "Arvaikheer", "Mandalgovi", "Dalanzadgad", "Züünkharaa", "Bulgan", "Altai", "Sükhbaatar", "Ondorkhaan", "Uliastai", "Tsetserleg", "Choir"],
        "Myanmar": ["Yangon", "Mandalay", "Naypyidaw", "Mawlamyine", "Bago", "Pathein", "Monywa", "Sittwe", "Meiktila", "Myeik", "Taunggyi", "Magway", "Lashio", "Pyay", "Hpa-An", "Dawei", "Myitkyina", "Pakokku", "Hinthada", "Taungoo"],
        "Nauru": ["Yaren", "Denigomodu", "Aiwo", "Anabar", "Anetan", "Anibare", "Baiti", "Boe", "Buada", "Ewa", "Ijuw", "Meneng", "Nibok", "Uaboe", "Location", "Ronave", "Settlement", "Moqua", "District", "Command Hill"],
        "Nepal": ["Kathmandu", "Pokhara", "Lalitpur", "Bharatpur", "Biratnagar", "Birgunj", "Dharan", "Hetauda", "Butwal", "Janakpur", "Nepalgunj", "Itahari", "Dhangadhi", "Bhaktapur", "Triyuga", "Tulsipur", "Ghorahi", "Lekhnath", "Kirtipur", "Siddharthanagar"],
        "Pakistan": ["Karachi", "Lahore", "Faisalabad", "Rawalpindi", "Multan", "Gujranwala", "Hyderabad", "Peshawar", "Abbottabad", "Islamabad", "Quetta", "Bahawalpur", "Sargodha", "Sialkot", "Sukkur", "Larkana", "Sheikhupura", "Rahim Yar Khan", "Jhang", "Dera Ghazi Khan"],
        "Palau": ["Ngerulmud", "Koror", "Meyungs", "Airai", "Melekeok", "Ngchesar", "Ngardmau", "Ngatpang", "Ngaremlengui", "Aimeliik", "Ngarchelong", "Ngiwal", "Ngaraard", "Kayangel", "Peleliu", "Angaur", "Sonsorol", "Hatohobei", "Kloulklubed", "Ollei"],
        "Papua New Guinea": ["Port Moresby", "Lae", "Mount Hagen", "Popondetta", "Madang", "Kokopo", "Mendi", "Wewak", "Goroka", "Kimbe", "Kundiawa", "Kavieng", "Daru", "Kerema", "Vanimo", "Wabag", "Arawa", "Alotau", "Tari", "Lorengau"],
        "Solomon Islands": ["Honiara", "Gizo", "Auki", "Munda", "Buala", "Kirakira", "Tulagi", "Lata", "Noro", "Taro Island", "Yandina", "Ringgi", "Tigoa", "Parasi", "Malu'u", "Seghe", "Afio", "Tawaraha", "Sasamunga", "Marau Sound"],
        "Sri Lanka": ["Colombo", "Dehiwala-Mount Lavinia", "Moratuwa", "Jaffna", "Negombo", "Kandy", "Pita Kotte", "Sri Jayewardenepura Kotte", "Kalmunai", "Trincomalee", "Galle", "Batticaloa", "Matara", "Badulla", "Point Pedro", "Kurunegala", "Anuradhapura", "Ratnapura", "Vavuniya", "Dambulla"],
        "Tajikistan": ["Dushanbe", "Khujand", "Kulob", "Qurghonteppa", "Istaravshan", "Konibodom", "Tursunzoda", "Isfara", "Vahdat", "Panjakent", "Khorugh", "Norak", "Rogun", "Dangara", "Chkalovsk", "Taboshar", "Hisor", "Nau", "Yovon", "Farkhor"],
        "Tonga": ["Nuku'alofa", "Neiafu", "Haveluloto", "Vaini", "Pangai", "Ohonua", "Hihifo", "Kolovai", "Mu'a", "Tatakamotonga", "Ha'atafu", "Niutoua", "Lapaha", "Holonga", "Havelu", "Pea", "Ha'asini", "Tofoa-Koloua", "Kolofo'ou", "Kanokupolu"],
        "Turkmenistan": ["Ashgabat", "Türkmenabat", "Daşoguz", "Mary", "Balkanabat", "Türkmenbaşy", "Tejen", "Abadan", "Serdar", "Gökdepe", "Saýat", "Baýramaly", "Kerki", "Yolöten", "Gazojak", "Magdanly", "Sarahs", "Bereket", "Atamyrat", "Boldumsaz"],
        "Uzbekistan": ["Tashkent", "Namangan", "Samarkand", "Andijan", "Bukhara", "Nukus", "Qarshi", "Kokand", "Fergana", "Margilan", "Jizzakh", "Urgench", "Angren", "Chirchiq", "Navoiy", "Termez", "Gulistan", "Qo'qon", "Denov", "Bekobod"],
        "Vanuatu": ["Port Vila", "Luganville", "Norsup", "Isangel", "Sola", "Lakatoro", "Port Olry", "Saratamata", "Lenakel", "Longana", "Lamap", "Maewo", "Vila", "Craig Cove", "North Efate", "South West Bay", "Pentecost", "Ambae", "Malakula", "Tanna"]
    ]
    
    static let states = statesAndCities.keys.sorted()
    
    static func cities(for state: String) -> [String] {
        return statesAndCities[state]?.sorted() ?? []
    }
    
    // Get states/provinces for a country
    static func statesOrProvinces(for country: String) -> [String] {
        switch country {
        case "United States":
            return states
        case "Canada":
            return canadianProvincesAndCities.keys.sorted()
        case "United Kingdom":
            return ukRegionsAndCities.keys.sorted()
        case "Australia":
            return australianStatesAndCities.keys.sorted()
        default:
            return [] // Countries without states/provinces
        }
    }
    
    // Get cities for a country and state/province (or just country if no states)
    static func cities(for country: String, state: String) -> [String] {
        switch country {
        case "United States":
            return statesAndCities[state]?.sorted() ?? []
        case "Canada":
            return canadianProvincesAndCities[state]?.sorted() ?? []
        case "United Kingdom":
            return ukRegionsAndCities[state]?.sorted() ?? []
        case "Australia":
            return australianStatesAndCities[state]?.sorted() ?? []
        default:
            return majorCitiesByCountry[country]?.sorted() ?? []
        }
    }
    
    // Check if a country uses states/provinces
    static func usesStates(country: String) -> Bool {
        return ["United States", "Canada", "United Kingdom", "Australia"].contains(country)
    }
}

